version: '2'
services:
    aluguel_carro-app:
        image: aluguel_carro
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aluguel_carro-mysql:3306/aluguel_carro?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aluguel_carro-mysql:
        extends:
            file: mysql.yml
            service: aluguel_carro-mysql
